// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace QAP.DataContext
{
    // Algorithm
    public class const_AlgorithmConfiguration : IEntityTypeConfiguration<const_Algorithm>
    {
        public void Configure(EntityTypeBuilder<const_Algorithm> builder)
        {
            builder.ToTable("Algorithm", "const");
            builder.HasKey(x => x.Id).HasName("PK_AlgorithmId");

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Alias).HasColumnName(@"Alias").HasColumnType("varchar(255)").IsRequired().IsUnicode(false).HasMaxLength(255);
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("ntext").IsRequired(false);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("ntext").IsRequired(false);

            builder.HasIndex(x => x.Alias).HasDatabaseName("UQ_AlgorithmAlias").IsUnique();
        }
    }

}
// </auto-generated>
