// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace QAP.DataContext
{
    // AlgorithmVersion
    public class const_AlgorithmVersionConfiguration : IEntityTypeConfiguration<const_AlgorithmVersion>
    {
        public void Configure(EntityTypeBuilder<const_AlgorithmVersion> builder)
        {
            builder.ToTable("AlgorithmVersion", "const");
            builder.HasKey(x => x.Id).HasName("PK_AlgorithmVersionId");

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Alias).HasColumnName(@"Alias").HasColumnType("varchar(255)").IsRequired().IsUnicode(false).HasMaxLength(255);
            builder.Property(x => x.Version).HasColumnName(@"Version").HasColumnType("int").IsRequired();
            builder.Property(x => x.AlgorithmId).HasColumnName(@"AlgorithmId").HasColumnType("int").IsRequired();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("ntext").IsRequired(false);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("ntext").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.const_Algorithm).WithMany(b => b.const_AlgorithmVersions).HasForeignKey(c => c.AlgorithmId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AlgorithmVersion_Algorithm");

            builder.HasIndex(x => new { x.AlgorithmId, x.Version }).HasDatabaseName("UQ_AlgorithmVersionAlgorithmIdAndVersion").IsUnique();
            builder.HasIndex(x => new { x.Alias, x.AlgorithmId }).HasDatabaseName("UQ_AlgorithmVersionAliasAndAlgorithmId").IsUnique();
        }
    }

}
// </auto-generated>
