// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace QAP.DataContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Problem
    public class ProblemConfiguration : IEntityTypeConfiguration<Problem>
    {
        public void Configure(EntityTypeBuilder<Problem> builder)
        {
            builder.ToTable("Problem", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_ProblemId");

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Size).HasColumnName(@"Size").HasColumnType("smallint").IsRequired();
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("varchar(255)").IsRequired().IsUnicode(false).HasMaxLength(255);
            builder.Property(x => x.MatrixA).HasColumnName(@"MatrixA").HasColumnType("varbinary(max)").IsRequired();
            builder.Property(x => x.MatrixB).HasColumnName(@"MatrixB").HasColumnType("varbinary(max)").IsRequired();
            builder.Property(x => x.Hash).HasColumnName(@"Hash").HasColumnType("binary(20)").IsRequired().HasMaxLength(20);
            builder.Property(x => x.Alias).HasColumnName(@"Alias").HasColumnType("varchar(255)").IsRequired(false).IsUnicode(false).HasMaxLength(255);
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(255)").IsRequired(false).HasMaxLength(255);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("ntext").IsRequired(false);

            builder.HasIndex(x => x.Hash).HasDatabaseName("IX_ProblemHash");
        }
    }

}
// </auto-generated>
