// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace QAP.DataContext
{
    // Session
    public class SessionConfiguration : IEntityTypeConfiguration<Session>
    {
        public void Configure(EntityTypeBuilder<Session> builder)
        {
            builder.ToTable("Session", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SessionId");

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.ProblemId).HasColumnName(@"ProblemId").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Problem).WithMany(b => b.Sessions).HasForeignKey(c => c.ProblemId).HasConstraintName("FK_Session_Problem");
        }
    }

}
// </auto-generated>
