// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace QAP.DataContext
{
    // Solution
    public class SolutionConfiguration : IEntityTypeConfiguration<Solution>
    {
        public void Configure(EntityTypeBuilder<Solution> builder)
        {
            builder.ToTable("Solution", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_SolutionId");

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Size).HasColumnName(@"Size").HasColumnType("smallint").IsRequired();
            builder.Property(x => x.Fitness).HasColumnName(@"Fitness").HasColumnType("real").IsRequired();
            builder.Property(x => x.Permutation).HasColumnName(@"Permutation").HasColumnType("varbinary(max)").IsRequired();
            builder.Property(x => x.ProblemId).HasColumnName(@"ProblemId").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Problem).WithMany(b => b.Solutions).HasForeignKey(c => c.ProblemId).HasConstraintName("FK_Solution_Problem");
        }
    }

}
// </auto-generated>
