// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class QAPDBContext : DbContext, IQAPDBContext
    {
        public QAPDBContext()
        {
        }

        public QAPDBContext(DbContextOptions<QAPDBContext> options)
            : base(options)
        {
        }

        public DbSet<AlgorithmVariation> AlgorithmVariations { get; set; } // AlgorithmVariation
        public DbSet<auth_User> auth_Users { get; set; } // User
        public DbSet<auth_UserLogin> auth_UserLogins { get; set; } // UserLogin
        public DbSet<Configuration> Configurations { get; set; } // Configuration
        public DbSet<const_Algorithm> const_Algorithms { get; set; } // Algorithm
        public DbSet<const_AlgorithmVersion> const_AlgorithmVersions { get; set; } // AlgorithmVersion
        public DbSet<const_State> const_States { get; set; } // State
        public DbSet<Multiverse> Multiverses { get; set; } // Multiverse
        public DbSet<Permutation> Permutations { get; set; } // Permutation
        public DbSet<ProblemInstance> ProblemInstances { get; set; } // ProblemInstance
        public DbSet<Session> Sessions { get; set; } // Session
        public DbSet<SessionAlgorithmVariation> SessionAlgorithmVariations { get; set; } // SessionAlgorithmVariation

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Server=.;Database=QAP;Trusted_Connection=True");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new AlgorithmVariationConfiguration());
            modelBuilder.ApplyConfiguration(new auth_UserConfiguration());
            modelBuilder.ApplyConfiguration(new auth_UserLoginConfiguration());
            modelBuilder.ApplyConfiguration(new ConfigurationConfiguration());
            modelBuilder.ApplyConfiguration(new const_AlgorithmConfiguration());
            modelBuilder.ApplyConfiguration(new const_AlgorithmVersionConfiguration());
            modelBuilder.ApplyConfiguration(new const_StateConfiguration());
            modelBuilder.ApplyConfiguration(new MultiverseConfiguration());
            modelBuilder.ApplyConfiguration(new PermutationConfiguration());
            modelBuilder.ApplyConfiguration(new ProblemInstanceConfiguration());
            modelBuilder.ApplyConfiguration(new SessionConfiguration());
            modelBuilder.ApplyConfiguration(new SessionAlgorithmVariationConfiguration());
        }

    }
}
// </auto-generated>
