// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace QAP.DataContext
{
    public class QAPDBContextFactory : IDesignTimeDbContextFactory<QAPDBContext>
    {
        public QAPDBContext CreateDbContext(string[] args)
        {
            return new QAPDBContext();
        }
    }
}
// </auto-generated>
