// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // AlgorithmVariation
    public class AlgorithmVariation
    {
        public int Id { get; set; } // Id (Primary key)
        public int AlgorithmVersionId { get; set; } // AlgorithmVersionId
        public int? ConfigurationId { get; set; } // ConfigurationId

        // Reverse navigation

        /// <summary>
        /// Child SessionAlgorithmVariations where [SessionAlgorithmVariation].[AlgorithmVariationId] point to this entity (FK_SessionAlgorithmVariation_AlgorithmVariation)
        /// </summary>
        public virtual ICollection<SessionAlgorithmVariation> SessionAlgorithmVariations { get; set; } // SessionAlgorithmVariation.FK_SessionAlgorithmVariation_AlgorithmVariation

        // Foreign keys

        /// <summary>
        /// Parent Configuration pointed by [AlgorithmVariation].([ConfigurationId]) (FK_AlgorithmVariation_Configuration)
        /// </summary>
        public virtual Configuration Configuration { get; set; } // FK_AlgorithmVariation_Configuration

        /// <summary>
        /// Parent const_AlgorithmVersion pointed by [AlgorithmVariation].([AlgorithmVersionId]) (FK_AlgorithmVariation_AlgorithmVersion)
        /// </summary>
        public virtual const_AlgorithmVersion const_AlgorithmVersion { get; set; } // FK_AlgorithmVariation_AlgorithmVersion

        public AlgorithmVariation()
        {
            SessionAlgorithmVariations = new List<SessionAlgorithmVariation>();
        }
    }

}
// </auto-generated>
