// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // User
    public class auth_User
    {
        public int Id { get; set; } // Id (Primary key)
        public string Alias { get; set; } // Alias (length: 255)
        public string HashedPassword { get; set; } // HashedPassword (length: 2147483647)
        public string Email { get; set; } // Email (length: 255)
        public string FullName { get; set; } // FullName (length: 255)
        public DateTime Timestamp { get; set; } // Timestamp

        // Reverse navigation

        /// <summary>
        /// Child AlgorithmVariations where [AlgorithmVariation].[UserId] point to this entity (FK_AlgorithmVariation_User)
        /// </summary>
        public virtual ICollection<AlgorithmVariation> AlgorithmVariations { get; set; } // AlgorithmVariation.FK_AlgorithmVariation_User

        /// <summary>
        /// Child auth_UserLogins where [UserLogin].[UserId] point to this entity (FK_UserLogin_User)
        /// </summary>
        public virtual ICollection<auth_UserLogin> auth_UserLogins { get; set; } // UserLogin.FK_UserLogin_User

        /// <summary>
        /// Child Multiverses where [Multiverse].[UserId] point to this entity (FK_Multiverse_User)
        /// </summary>
        public virtual ICollection<Multiverse> Multiverses { get; set; } // Multiverse.FK_Multiverse_User

        /// <summary>
        /// Child ProblemInstances where [ProblemInstance].[UserId] point to this entity (FK_ProblemInstance_User)
        /// </summary>
        public virtual ICollection<ProblemInstance> ProblemInstances { get; set; } // ProblemInstance.FK_ProblemInstance_User

        public auth_User()
        {
            Timestamp = DateTime.Now;
            AlgorithmVariations = new List<AlgorithmVariation>();
            Multiverses = new List<Multiverse>();
            ProblemInstances = new List<ProblemInstance>();
            auth_UserLogins = new List<auth_UserLogin>();
        }
    }

}
// </auto-generated>
