// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // UserLogin
    public class auth_UserLogin
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public string Token { get; set; } // Token (length: 2147483647)
        public string UserAgent { get; set; } // UserAgent (length: 2147483647)
        public DateTime ValidUntil { get; set; } // ValidUntil
        public bool Enabled { get; set; } // Enabled
        public DateTime Timestamp { get; set; } // Timestamp

        // Foreign keys

        /// <summary>
        /// Parent auth_User pointed by [UserLogin].([UserId]) (FK_UserLogin_User)
        /// </summary>
        public virtual auth_User auth_User { get; set; } // FK_UserLogin_User

        public auth_UserLogin()
        {
            Timestamp = DateTime.Now;
        }
    }

}
// </auto-generated>
