// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Configuration
    public class Configuration
    {
        public int Id { get; set; } // Id (Primary key)
        public string Value { get; set; } // Value (length: 1073741823)

        // Reverse navigation

        /// <summary>
        /// Child AlgorithmVariations where [AlgorithmVariation].[ConfigurationId] point to this entity (FK_AlgorithmVariation_Configuration)
        /// </summary>
        public virtual ICollection<AlgorithmVariation> AlgorithmVariations { get; set; } // AlgorithmVariation.FK_AlgorithmVariation_Configuration

        /// <summary>
        /// Child SessionAlgorithmVariations where [SessionAlgorithmVariation].[ConfigurationId] point to this entity (FK_SessionAlgorithmVariation_Configuration)
        /// </summary>
        public virtual ICollection<SessionAlgorithmVariation> SessionAlgorithmVariations { get; set; } // SessionAlgorithmVariation.FK_SessionAlgorithmVariation_Configuration

        public Configuration()
        {
            AlgorithmVariations = new List<AlgorithmVariation>();
            SessionAlgorithmVariations = new List<SessionAlgorithmVariation>();
        }
    }

}
// </auto-generated>
