// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // AlgorithmVersion
    public class const_AlgorithmVersion
    {
        public int Id { get; set; } // Id (Primary key)
        public string Alias { get; set; } // Alias (length: 255)
        public int Version { get; set; } // Version
        public int AlgorithmId { get; set; } // AlgorithmId
        public string Title { get; set; } // Title (length: 1073741823)
        public string Description { get; set; } // Description (length: 1073741823)

        // Reverse navigation

        /// <summary>
        /// Child AlgorithmVariations where [AlgorithmVariation].[AlgorithmVersionId] point to this entity (FK_AlgorithmVariation_AlgorithmVersion)
        /// </summary>
        public virtual ICollection<AlgorithmVariation> AlgorithmVariations { get; set; } // AlgorithmVariation.FK_AlgorithmVariation_AlgorithmVersion

        // Foreign keys

        /// <summary>
        /// Parent const_Algorithm pointed by [AlgorithmVersion].([AlgorithmId]) (FK_AlgorithmVersion_Algorithm)
        /// </summary>
        public virtual const_Algorithm const_Algorithm { get; set; } // FK_AlgorithmVersion_Algorithm

        public const_AlgorithmVersion()
        {
            AlgorithmVariations = new List<AlgorithmVariation>();
        }
    }

}
// </auto-generated>
