// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // State
    public class const_State
    {
        public int Id { get; set; } // Id (Primary key)
        public string Alias { get; set; } // Alias (length: 255)
        public string Title { get; set; } // Title (length: 1073741823)
        public string Description { get; set; } // Description (length: 1073741823)

        // Reverse navigation

        /// <summary>
        /// Child SessionAlgorithmVersions where [SessionAlgorithmVersion].[StateId] point to this entity (FK_SessionAlgorithmVersion_State)
        /// </summary>
        public virtual ICollection<SessionAlgorithmVersion> SessionAlgorithmVersions { get; set; } // SessionAlgorithmVersion.FK_SessionAlgorithmVersion_State

        public const_State()
        {
            SessionAlgorithmVersions = new List<SessionAlgorithmVersion>();
        }
    }

}
// </auto-generated>
