// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Algorithm
    public class const_Algorithm
    {
        public int Id { get; set; } // Id (Primary key)
        public string Alias { get; set; } // Alias (length: 255)
        public string Title { get; set; } // Title (length: 1073741823)
        public string Description { get; set; } // Description (length: 1073741823)

        // Reverse navigation

        /// <summary>
        /// Child AlgorithmVersions where [AlgorithmVersion].[AlgorithmId] point to this entity (FK_AlgorithmVersion_Algorithm)
        /// </summary>
        public virtual ICollection<AlgorithmVersion> AlgorithmVersions { get; set; } // AlgorithmVersion.FK_AlgorithmVersion_Algorithm

        public const_Algorithm()
        {
            AlgorithmVersions = new List<AlgorithmVersion>();
        }
    }

}
// </auto-generated>
