// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Permutation
    public class Permutation
    {
        public long Id { get; set; } // Id (Primary key)
        public long Cost { get; set; } // Cost
        public byte[] Value { get; set; } // Value
        public int SessionAlgorithmVariationId { get; set; } // SessionAlgorithmVariationId
        public int Iteration { get; set; } // Iteration
        public byte Trial { get; set; } // Trial
        public DateTime CreatedAt { get; set; } // CreatedAt

        // Reverse navigation

        /// <summary>
        /// Child ProblemInstances where [ProblemInstance].[PermutationId] point to this entity (FK_ProblemInstance_Permutation)
        /// </summary>
        public virtual ICollection<ProblemInstance> ProblemInstances { get; set; } // ProblemInstance.FK_ProblemInstance_Permutation

        /// <summary>
        /// Child SessionAlgorithmVariations where [SessionAlgorithmVariation].[PermutationId] point to this entity (FK_SessionAlgorithmVariation_Permutation)
        /// </summary>
        public virtual ICollection<SessionAlgorithmVariation> SessionAlgorithmVariations { get; set; } // SessionAlgorithmVariation.FK_SessionAlgorithmVariation_Permutation

        // Foreign keys

        /// <summary>
        /// Parent SessionAlgorithmVariation pointed by [Permutation].([SessionAlgorithmVariationId]) (FK_Permutation_SessionAlgorithmVariation)
        /// </summary>
        public virtual SessionAlgorithmVariation SessionAlgorithmVariation { get; set; } // FK_Permutation_SessionAlgorithmVariation

        public Permutation()
        {
            CreatedAt = DateTime.Now;
            ProblemInstances = new List<ProblemInstance>();
            SessionAlgorithmVariations = new List<SessionAlgorithmVariation>();
        }
    }

}
// </auto-generated>
