// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Problem
    public class Problem
    {
        public int Id { get; set; } // Id (Primary key)
        public int Size { get; set; } // Size
        public byte[] MatrixA { get; set; } // MatrixA
        public byte[] MatrixB { get; set; } // MatrixB
        public byte[] Hash { get; set; } // Hash (length: 32)
        public DateTime CreatedAt { get; set; } // CreatedAt
        public string Alias { get; set; } // Alias (length: 255)
        public string Title { get; set; } // Title (length: 1073741823)
        public string Description { get; set; } // Description (length: 1073741823)

        // Reverse navigation

        /// <summary>
        /// Child Solutions where [Solution].[ProblemId] point to this entity (FK_Solution_Problem)
        /// </summary>
        public virtual ICollection<Solution> Solutions { get; set; } // Solution.FK_Solution_Problem

        public Problem()
        {
            CreatedAt = DateTime.Now;
            Solutions = new List<Solution>();
        }
    }

}
// </auto-generated>
