// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Problem
    public class Problem
    {
        public int Id { get; set; } // Id (Primary key)
        public int Size { get; set; } // Size
        public byte[] MatrixA { get; set; } // MatrixA
        public byte[] MatrixB { get; set; } // MatrixB
        public byte[] Hash { get; set; } // Hash (length: 32)
        public DateTime CreatedAt { get; set; } // CreatedAt
        public string Alias { get; set; } // Alias (length: 255)
        public string Title { get; set; } // Title (length: 1073741823)
        public string Description { get; set; } // Description (length: 1073741823)
        public long? InitialBestKnownCost { get; set; } // InitialBestKnownCost
        public long? AllTimeBestKnownCost { get; set; } // AllTimeBestKnownCost

        // Reverse navigation

        /// <summary>
        /// Child Sessions where [Session].[ProblemId] point to this entity (FK_Session_Problem)
        /// </summary>
        public virtual ICollection<Session> Sessions { get; set; } // Session.FK_Session_Problem

        public Problem()
        {
            CreatedAt = DateTime.Now;
            Sessions = new List<Session>();
        }
    }

}
// </auto-generated>
