// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Session
    public class Session
    {
        public int Id { get; set; } // Id (Primary key)
        public int MultiverseId { get; set; } // MultiverseId
        public int ProblemInstanceId { get; set; } // ProblemInstanceId

        // Reverse navigation

        /// <summary>
        /// Child SessionAlgorithmVariations where [SessionAlgorithmVariation].[SessionId] point to this entity (FK_SessionAlgorithmVariation_Session)
        /// </summary>
        public virtual ICollection<SessionAlgorithmVariation> SessionAlgorithmVariations { get; set; } // SessionAlgorithmVariation.FK_SessionAlgorithmVariation_Session

        // Foreign keys

        /// <summary>
        /// Parent Multiverse pointed by [Session].([MultiverseId]) (FK_Session_Multiverse)
        /// </summary>
        public virtual Multiverse Multiverse { get; set; } // FK_Session_Multiverse

        /// <summary>
        /// Parent ProblemInstance pointed by [Session].([ProblemInstanceId]) (FK_Session_ProblemInstance)
        /// </summary>
        public virtual ProblemInstance ProblemInstance { get; set; } // FK_Session_ProblemInstance

        public Session()
        {
            SessionAlgorithmVariations = new List<SessionAlgorithmVariation>();
        }
    }

}
// </auto-generated>
