// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Session
    public class Session
    {
        public int Id { get; set; } // Id (Primary key)
        public int MultiverseId { get; set; } // MultiverseId
        public int ProblemId { get; set; } // ProblemId

        // Reverse navigation

        /// <summary>
        /// Child SessionAlgorithmVersions where [SessionAlgorithmVersion].[SessionId] point to this entity (FK_SessionAlgorithmVersion_Session)
        /// </summary>
        public virtual ICollection<SessionAlgorithmVersion> SessionAlgorithmVersions { get; set; } // SessionAlgorithmVersion.FK_SessionAlgorithmVersion_Session

        // Foreign keys

        /// <summary>
        /// Parent Multiverse pointed by [Session].([MultiverseId]) (FK_Session_Multiverse)
        /// </summary>
        public virtual Multiverse Multiverse { get; set; } // FK_Session_Multiverse

        /// <summary>
        /// Parent Problem pointed by [Session].([ProblemId]) (FK_Session_Problem)
        /// </summary>
        public virtual Problem Problem { get; set; } // FK_Session_Problem

        public Session()
        {
            SessionAlgorithmVersions = new List<SessionAlgorithmVersion>();
        }
    }

}
// </auto-generated>
