// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // SessionAlgorithmVariation
    public class SessionAlgorithmVariation
    {
        public int Id { get; set; } // Id (Primary key)
        public int SessionId { get; set; } // SessionId
        public int AlgorithmVariationId { get; set; } // AlgorithmVariationId
        public int? ConfigurationId { get; set; } // ConfigurationId
        public long? PermutationId { get; set; } // PermutationId

        // Reverse navigation

        /// <summary>
        /// Child Permutations where [Permutation].[SessionAlgorithmVariationId] point to this entity (FK_Permutation_SessionAlgorithmVariation)
        /// </summary>
        public virtual ICollection<Permutation> Permutations { get; set; } // Permutation.FK_Permutation_SessionAlgorithmVariation

        // Foreign keys

        /// <summary>
        /// Parent AlgorithmVariation pointed by [SessionAlgorithmVariation].([AlgorithmVariationId]) (FK_SessionAlgorithmVariation_AlgorithmVariation)
        /// </summary>
        public virtual AlgorithmVariation AlgorithmVariation { get; set; } // FK_SessionAlgorithmVariation_AlgorithmVariation

        /// <summary>
        /// Parent Configuration pointed by [SessionAlgorithmVariation].([ConfigurationId]) (FK_SessionAlgorithmVariation_Configuration)
        /// </summary>
        public virtual Configuration Configuration { get; set; } // FK_SessionAlgorithmVariation_Configuration

        /// <summary>
        /// Parent Permutation pointed by [SessionAlgorithmVariation].([PermutationId]) (FK_SessionAlgorithmVariation_Permutation)
        /// </summary>
        public virtual Permutation Permutation { get; set; } // FK_SessionAlgorithmVariation_Permutation

        /// <summary>
        /// Parent Session pointed by [SessionAlgorithmVariation].([SessionId]) (FK_SessionAlgorithmVariation_Session)
        /// </summary>
        public virtual Session Session { get; set; } // FK_SessionAlgorithmVariation_Session

        public SessionAlgorithmVariation()
        {
            Permutations = new List<Permutation>();
        }
    }

}
// </auto-generated>
