// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // SessionAlgorithm
    public class SessionAlgorithm
    {
        public int Id { get; set; } // Id (Primary key)
        public int SessionId { get; set; } // SessionId
        public short AlgorithmId { get; set; } // AlgorithmId
        public string Info { get; set; } // Info (length: 1073741823)
        public DateTime CreatedAt { get; set; } // CreatedAt

        // Reverse navigation

        /// <summary>
        /// Child Solutions where [Solution].[SessionAlgorithmId] point to this entity (FK_Solution_SessionAlgorithm)
        /// </summary>
        public virtual ICollection<Solution> Solutions { get; set; } // Solution.FK_Solution_SessionAlgorithm

        // Foreign keys

        /// <summary>
        /// Parent const_Algorithm pointed by [SessionAlgorithm].([AlgorithmId]) (FK_SessionAlgorithm_Algorithm)
        /// </summary>
        public virtual const_Algorithm const_Algorithm { get; set; } // FK_SessionAlgorithm_Algorithm

        /// <summary>
        /// Parent Session pointed by [SessionAlgorithm].([SessionId]) (FK_SessionAlgorithm_Session)
        /// </summary>
        public virtual Session Session { get; set; } // FK_SessionAlgorithm_Session

        public SessionAlgorithm()
        {
            CreatedAt = DateTime.Now;
            Solutions = new List<Solution>();
        }
    }

}
// </auto-generated>
