// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Session
    public class Session
    {
        public int Id { get; set; } // Id (Primary key)
        public int ProblemId { get; set; } // ProblemId
        public DateTime CreatedAt { get; set; } // CreatedAt

        // Reverse navigation

        /// <summary>
        /// Child SessionAlgorithms where [SessionAlgorithm].[SessionId] point to this entity (FK_SessionAlgorithm_Session)
        /// </summary>
        public virtual ICollection<SessionAlgorithm> SessionAlgorithms { get; set; } // SessionAlgorithm.FK_SessionAlgorithm_Session

        // Foreign keys

        /// <summary>
        /// Parent Problem pointed by [Session].([ProblemId]) (FK_Session_Problem)
        /// </summary>
        public virtual Problem Problem { get; set; } // FK_Session_Problem

        public Session()
        {
            CreatedAt = DateTime.Now;
            SessionAlgorithms = new List<SessionAlgorithm>();
        }
    }

}
// </auto-generated>
