// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // SessionAlgorithmVersion
    public class SessionAlgorithmVersion
    {
        public int Id { get; set; } // Id (Primary key)
        public int SessionId { get; set; } // SessionId
        public int AlgorithmVersionId { get; set; } // AlgorithmVersionId
        public int StateId { get; set; } // StateId
        public string Configuration { get; set; } // Configuration (length: 1073741823)
        public long? Seed { get; set; } // Seed
        public long? PermutationId { get; set; } // PermutationId

        // Reverse navigation

        /// <summary>
        /// Child Permutations where [Permutation].[SessionAlgorithmVersionId] point to this entity (FK_Permutation_SessionAlgorithmVersion)
        /// </summary>
        public virtual ICollection<Permutation> Permutations { get; set; } // Permutation.FK_Permutation_SessionAlgorithmVersion

        // Foreign keys

        /// <summary>
        /// Parent AlgorithmVersion pointed by [SessionAlgorithmVersion].([AlgorithmVersionId]) (FK_SessionAlgorithmVersion_AlgorithmVersion)
        /// </summary>
        public virtual AlgorithmVersion AlgorithmVersion { get; set; } // FK_SessionAlgorithmVersion_AlgorithmVersion

        /// <summary>
        /// Parent const_State pointed by [SessionAlgorithmVersion].([StateId]) (FK_SessionAlgorithmVersion_State)
        /// </summary>
        public virtual const_State const_State { get; set; } // FK_SessionAlgorithmVersion_State

        /// <summary>
        /// Parent Permutation pointed by [SessionAlgorithmVersion].([PermutationId]) (FK_SessionAlgorithmVersion_Permutation)
        /// </summary>
        public virtual Permutation Permutation { get; set; } // FK_SessionAlgorithmVersion_Permutation

        /// <summary>
        /// Parent Session pointed by [SessionAlgorithmVersion].([SessionId]) (FK_SessionAlgorithmVersion_Session)
        /// </summary>
        public virtual Session Session { get; set; } // FK_SessionAlgorithmVersion_Session

        public SessionAlgorithmVersion()
        {
            Permutations = new List<Permutation>();
        }
    }

}
// </auto-generated>
