// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Solution
    public class Solution
    {
        public long Id { get; set; } // Id (Primary key)
        public long Cost { get; set; } // Cost
        public byte[] Permutation { get; set; } // Permutation
        public int SessionAlgorithmId { get; set; } // SessionAlgorithmId
        public DateTime CreatedAt { get; set; } // CreatedAt

        // Foreign keys

        /// <summary>
        /// Parent SessionAlgorithm pointed by [Solution].([SessionAlgorithmId]) (FK_Solution_SessionAlgorithm)
        /// </summary>
        public virtual SessionAlgorithm SessionAlgorithm { get; set; } // FK_Solution_SessionAlgorithm

        public Solution()
        {
            CreatedAt = DateTime.Now;
        }
    }

}
// </auto-generated>
