// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace QAP.DataContext
{
    // Solution
    public class Solution
    {
        public long Id { get; set; } // Id (Primary key)
        public short Size { get; set; } // Size
        public float Fitness { get; set; } // Fitness
        public byte[] Permutation { get; set; } // Permutation
        public int ProblemId { get; set; } // ProblemId

        // Foreign keys

        /// <summary>
        /// Parent Problem pointed by [Solution].([ProblemId]) (FK_Solution_Problem)
        /// </summary>
        public virtual Problem Problem { get; set; } // FK_Solution_Problem
    }

}
// </auto-generated>
